version: '3.8'

services:
  web:
    image: python:3.11-slim
    container_name: {{.ProjectName}}_web
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-myapp}
      REDIS_URL: redis://redis:6379/0
      DEBUG: ${DEBUG:-True}
    depends_on:
      - db
      - redis
    networks:
      - django-network

  db:
    image: postgres:16-alpine
    container_name: {{.ProjectName}}_db
    environment:
      POSTGRES_DB: ${DB_NAME:-myapp}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django-network

  redis:
    image: redis:7-alpine
    container_name: {{.ProjectName}}_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - django-network

  celery:
    image: python:3.11-slim
    container_name: {{.ProjectName}}_celery
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "pip install -r requirements.txt && celery -A myapp worker -l info"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-myapp}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - django-network

volumes:
  postgres-data:
  redis-data:

networks:
  django-network:
    driver: bridge
