version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: {{.ProjectName}}_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mean-network

  backend:
    image: node:20-alpine
    container_name: {{.ProjectName}}_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/
      NODE_ENV: development
    depends_on:
      - mongodb
    networks:
      - mean-network

  frontend:
    image: node:20-alpine
    container_name: {{.ProjectName}}_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
    environment:
      API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - mean-network

volumes:
  mongo-data:

networks:
  mean-network:
    driver: bridge
