version: '3.8'

services:
  web:
    image: ruby:3.2-slim
    container_name: {{.ProjectName}}_web
    working_dir: /app
    volumes:
      - ./app:/app
      - bundle-cache:/usr/local/bundle
    command: sh -c "bundle install && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-myapp}
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: ${RAILS_ENV:-development}
    depends_on:
      - db
      - redis
    networks:
      - rails-network

  db:
    image: postgres:16-alpine
    container_name: {{.ProjectName}}_db
    environment:
      POSTGRES_DB: ${DB_NAME:-myapp}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rails-network

  redis:
    image: redis:7-alpine
    container_name: {{.ProjectName}}_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rails-network

  sidekiq:
    image: ruby:3.2-slim
    container_name: {{.ProjectName}}_sidekiq
    working_dir: /app
    volumes:
      - ./app:/app
      - bundle-cache:/usr/local/bundle
    command: sh -c "bundle install && bundle exec sidekiq"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-myapp}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - rails-network

volumes:
  postgres-data:
  redis-data:
  bundle-cache:

networks:
  rails-network:
    driver: bridge
